db.hotels.insertMany([
  {
    id: 1,
    name: "Grand Hotel",
    address: "123 Main St",
    city: "Springfield",
    state: "IL",
    country: "USA",
    zip_code: "62701",
    phone_number: "+1-555-1234",
    email: "contact@grandhotel.com",
    rating: 4.5,
    available_rooms: 20,
    price_per_night: 150.0,
    amenities: ["Free WiFi", "Pool", "Gym"],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    name: "Cozy Inn",
    address: "456 Elm St",
    city: "Oakville",
    state: "CA",
    country: "USA",
    zip_code: "94016",
    phone_number: "+1-555-5678",
    email: "info@cozyinn.com",
    rating: 3.8,
    available_rooms: 15,
    price_per_night: 90.0,
    amenities: ["Free Breakfast", "Parking"],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 3,
    name: "Luxury Suites",
    address: "789 Oak Ave",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
    zip_code: "90001",
    phone_number: "+1-555-9876",
    email: "reservations@luxurysuites.com",
    rating: 4.8,
    available_rooms: 10,
    price_per_night: 300.0,
    amenities: ["Spa", "Concierge", "Fine Dining"],
    created_at: new Date(),
    updated_at: new Date(),
  },
]);
